project:
  type: default
  output-dir: _output

bibliography: references.bib
csl: nature-communications.csl

format:
  docx:
    number-sections: false
  pdf:
    pdf-engine: xelatex
    documentclass: article
    geometry: margin=1in
    include-in-header: header.tex
    number-sections: false
    keep-tex: true
